federation_version: 2
subgraphs:
  profile:
    routing_url: http://localhost:5010/
    schema:
      subgraph_url: http://localhost:5010/
  products:
    routing_url: http://localhost:5020/
    schema:
      subgraph_url: http://localhost:5020/
  shipping:
    routing_url: http://localhost:5030/
    schema:
      subgraph_url: http://localhost:5030/
